# Generated by Django 5.1.6 on 2026-02-27 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_anilla', models.CharField(max_length=100)),
                ('anio_nacimiento', models.PositiveSmallIntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('variedad', models.CharField(choices=[('SALMON', 'Salmón'), ('PLATA', 'Plata'), ('OTRA', 'Otra')], default='SALMON', max_length=20)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('historico_pesos', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('AÑADIDO', 'Añadido'), ('APROBADO', 'Aprobado'), ('EVALUADO', 'Evaluado'), ('RECHAZADO', 'Rechazado'), ('SOCIO_EN_BAJA', 'Socio en baja')], default='AÑADIDO', max_length=20)),
                ('razon_rechazo', models.TextField(blank=True, default='')),
                ('candidato_reproductor', models.BooleanField(default=False)),
                ('reproductor_aprobado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('madre_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='animals.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'animals_animal',
            },
        ),
    ]
