# Generated by Django 5.1.6 on 2026-02-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('animals', '0001_initial'),
        ('lotes', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='madre_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='lotes.lote'),
        ),
        migrations.AddField(
            model_name='animal',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='animals.animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='accounts.socio'),
        ),
        migrations.AddField(
            model_name='animal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tenant', 'socio'], name='animals_ani_tenant__55be7e_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tenant', 'estado'], name='animals_ani_tenant__2a0ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['tenant', 'variedad'], name='animals_ani_tenant__5a2a4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='animal',
            unique_together={('tenant', 'numero_anilla', 'anio_nacimiento')},
        ),
    ]
