# Generated by Django 5.1.6 on 2026-02-27 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_initial'),
        ('granjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='granja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='granjas.granja'),
        ),
    ]
