# Generated by Django 5.1.6 on 2026-03-23 22:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_motivo_baja_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='alerta_anilla',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('AÑADIDO', 'Añadido'), ('APROBADO', 'Aprobado'), ('EVALUADO', 'Evaluado'), ('RECHAZADO', 'Rechazado'), ('SOCIO_EN_BAJA', 'Socio en baja'), ('BAJA', 'Baja')], default='AÑADIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='motivobaja',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
