# Generated by Django 5.1.6 on 2026-04-13 10:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_add_estado_modificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ganaderianacimientomap',
            options={'verbose_name': 'Mapa ganadería nacimiento', 'verbose_name_plural': 'Mapas ganadería nacimiento'},
        ),
        migrations.AlterModelOptions(
            name='loteexternomap',
            options={'verbose_name': 'Mapa lote externo', 'verbose_name_plural': 'Mapas lote externo'},
        ),
        migrations.RemoveField(
            model_name='ganaderianacimientomap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ganaderianacimientomap',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loteexternomap',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loteexternomap',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='animal',
            name='variedad',
            field=models.CharField(choices=[('SALMON', 'Salmón'), ('PLATA', 'Plata'), ('SIN_DEFINIR', 'Sin Definir')], default='SALMON', max_length=20),
        ),
        migrations.AlterField(
            model_name='ganaderianacimientomap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loteexternomap',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
