# Generated by Django 5.1.6 on 2026-02-27 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('animals', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('macho', models.ForeignKey(limit_choices_to={'sexo': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_como_macho', to='animals.animal')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='accounts.socio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Lote de Cría',
                'verbose_name_plural': 'Lotes de Cría',
                'db_table': 'lotes_lote',
            },
        ),
        migrations.CreateModel(
            name='LoteHembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hembra', models.ForeignKey(limit_choices_to={'sexo': 'H'}, on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotes.lote')),
            ],
            options={
                'db_table': 'lotes_lote_hembras',
                'unique_together': {('lote', 'hembra')},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='hembras',
            field=models.ManyToManyField(blank=True, related_name='lotes_como_hembra', through='lotes.LoteHembra', to='animals.animal'),
        ),
    ]
