# Generated by Django 5.1.6 on 2026-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_reset_socio_passwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ANIMAL_APROBADO', 'Animal aprobado'), ('ANIMAL_RECHAZADO', 'Animal rechazado'), ('REALTA_APROBADA', 'Re-alta aprobada'), ('REALTA_DENEGADA', 'Re-alta denegada'), ('REPRODUCTOR_APROBADO', 'Reproductor aprobado'), ('REPRODUCTOR_DENEGADO', 'Reproductor denegado'), ('CAMBIO_DATOS_APROBADO', 'Cambio de datos aprobado'), ('CAMBIO_DATOS_DENEGADO', 'Cambio de datos denegado'), ('CUOTA_PENDIENTE', 'Cuota anual pendiente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccesslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='useraccesslog',
            name='user_role',
            field=models.CharField(blank=True, default='', help_text='superadmin | gestion | socio', max_length=20),
        ),
    ]
