# Generated by Django 5.1.6 on 2026-02-27 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflicto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_anilla', models.CharField(max_length=100)),
                ('anio_nacimiento', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESUELTO', 'Resuelto'), ('DESCARTADO', 'Descartado')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('socio_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos_actual', to='accounts.socio')),
                ('socio_reclamante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos_reclamante', to='accounts.socio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Conflicto',
                'verbose_name_plural': 'Conflictos',
                'db_table': 'conflicts_conflicto',
            },
        ),
    ]
