# Generated by Django 5.1.6 on 2026-02-27 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('codigo_rega', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='granjas', to='accounts.socio')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Granja',
                'verbose_name_plural': 'Granjas',
                'db_table': 'granjas_granja',
                'indexes': [models.Index(fields=['tenant', 'socio'], name='granjas_gra_tenant__5a8305_idx')],
                'unique_together': {('tenant', 'socio', 'nombre')},
            },
        ),
    ]
