# Generated by Django 5.1.6 on 2026-04-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriaanimal',
            options={'verbose_name': 'Animal Auditado', 'verbose_name_plural': 'Animales Auditados'},
        ),
        migrations.AlterModelOptions(
            name='auditoriasession',
            options={'ordering': ['-fecha_planificada'], 'verbose_name': 'Auditoría', 'verbose_name_plural': 'Auditorías'},
        ),
        migrations.AlterModelOptions(
            name='criterioevaluacion',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Criterio de Evaluación', 'verbose_name_plural': 'Criterios de Evaluación'},
        ),
        migrations.AlterModelOptions(
            name='preguntainstalacion',
            options={'ordering': ['orden'], 'verbose_name': 'Pregunta de Instalación', 'verbose_name_plural': 'Preguntas de Instalación'},
        ),
    ]
