# Generated by Django 5.1.6 on 2026-03-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_smtp_granjas_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='anilla_sizes',
            field=models.JSONField(blank=True, default=list, help_text='Tamaños disponibles. Ej: [{"mm":"18","sexo":"H"},{"mm":"20","sexo":"M"}]'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='granjas_enabled',
            field=models.BooleanField(default=True, help_text='Habilita granjas múltiples para socios.'),
        ),
    ]
