# Generated by Django 5.1.6 on 2026-02-27 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('INVENTORY', 'Inventario'), ('INDIVIDUAL', 'Ficha Individual'), ('GENEALOGY_CERT', 'Certificado Genealógico'), ('LIBRO_GENEALOGICO', 'Libro Genealógico (Excel)'), ('CATALOGO_REPRODUCTORES', 'Catálogo Reproductores (PDF)')], max_length=40)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('file_key', models.CharField(blank=True, default='', max_length=500)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_jobs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Report Job',
                'verbose_name_plural': 'Report Jobs',
                'db_table': 'reports_reportjob',
            },
        ),
    ]
